[package]
name = "raycli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = { path = "../raylib" }
image = { version = "0.24"}
rayon = "1.5"